CREATE DATABASE IF NOT EXISTS webxemay;
USE webxemay;

-- Bảng Quản Lý
CREATE TABLE QuanLy (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    HoTen VARCHAR(255),
    SDT VARCHAR(20)
) AUTO_INCREMENT = 10000;

-- Bảng Nhân Viên
CREATE TABLE NhanVien (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    HoTen VARCHAR(255),
    SDT VARCHAR(20),
    ID_QL INT,
    FOREIGN KEY (ID_QL) REFERENCES QuanLy(ID)
) AUTO_INCREMENT = 10000;

-- Bảng Khách Hàng
CREATE TABLE KhachHang (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    HoTen VARCHAR(255),
    SDT VARCHAR(20),
    DiaChi TEXT
) AUTO_INCREMENT = 10000;

-- Bảng Loại Sản Phẩm
CREATE TABLE LoaiSanPham (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TenLoaiSanPham VARCHAR(255),
    MoTa VARCHAR(500)
) AUTO_INCREMENT = 10000;

-- Bảng Sản Phẩm
CREATE TABLE SanPham (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TenSanPham VARCHAR(255),
    Gia FLOAT,
    ID_LSP INT,
    ID_GH INT,
    FOREIGN KEY (ID_LSP) REFERENCES LoaiSanPham(ID),
    FOREIGN KEY (ID_GH) REFERENCES NhanVien(ID)
) AUTO_INCREMENT = 10000;

-- Bảng Thông Số
CREATE TABLE ThongSo (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DongCo VARCHAR(100),
    DungTich VARCHAR(100),
    CongSuat VARCHAR(100),
    ID_SP INT,
    FOREIGN KEY (ID_SP) REFERENCES SanPham(ID)
) AUTO_INCREMENT = 10000;

-- Bảng Tài Khoản
CREATE TABLE TaiKhoan (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TenDangNhap VARCHAR(100),
    MatKhau VARCHAR(100),
    LoaiTaiKhoan VARCHAR(50),
    ID_KH INT,
    ID_NV INT,
    FOREIGN KEY (ID_KH) REFERENCES KhachHang(ID),
    FOREIGN KEY (ID_NV) REFERENCES NhanVien(ID)
) AUTO_INCREMENT = 10000;

-- Bảng Tin Tức
CREATE TABLE TinTuc (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TieuDe VARCHAR(255),
    NoiDung VARCHAR(1000),
    NgayDang DATETIME,
    ID_NV INT,
    FOREIGN KEY (ID_NV) REFERENCES NhanVien(ID)
) AUTO_INCREMENT = 10000;
